language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - nodeenv -p -n 6.10.2
  - npm install serverless@1.12.1 -g
  - cd serverless-google-calendar-export/
  - npm install --save
  - sls requirements install
  - sls package